Se completo el flujo de compra con MercadoPago incluyendo arreglos es…
leocouar/White-label pull request #149
Opened 2024-01-23 19:09 UTC by alangabrielmedina

…teticos.

NOTA IMPORTANTE: es necesario que se realizen cambios en el backend - **actualmente esto no va a funcionar.**

2024-01-23 20:37 UTC, leocouar commented on components/Nav.js
eliminar logs

2024-01-23 20:38 UTC, leocouar commented on components/cart/CartTable.js
Mucho codigo comentado

2024-01-23 20:47 UTC, leocouar reviewed
Corrección de los siguientes cambios

2024-01-23 20:47 UTC, leocouar commented on components/checkout/List.js
Quitar los logs

2024-01-23 20:47 UTC, leocouar commented on context/Store.js
Asincronía no necesaria. Cuando se emplean los las funciones async hay que tener en cuenta el funcionamiento de esta, la asincronia se usa generalmente cuando demora algún tipo de llamado y se tiene que esperar en otro lado.

2024-01-23 20:47 UTC, leocouar commented on pages/cart.js
session?.user?.username de esta forma evitas si por algún caso falla la session

2024-01-24 17:22 UTC, leocouar commented
Link de vercel para la rama de mercadopagocomercio: https://white-label-git-mercadopagocomercio-leokhfm.vercel.app/

2024-01-24 19:27 UTC, candelamattioli requested changes
- Cuando abris el sitio lo primero que carga es el banner con los comercios
- Se achico demasiado el buscador
- Cuando se navega por el inicio no se cargan en su totalidad los productos, sólo si bajas hasta abajo del todo, recién ahí aparecen todos los productos.
- También si se baja hasta abajo del todo el inicio se sube hasta arriba solo, otro ejemplo es que si estas en la sección del banner de comercios unos segundos también se sube.
- Cuando agregas x cantidad de productos, no se puede borrar cantidades
- Al agregar cierta cantidad de un producto al carrito de compra estando logueado, se cierra sesión y en el carrito aún queda la cantidad de productos seleccionados, también sucede cuando ingresas un usuario nuevo
- En responsive no aparece la opción de Iniciar Sesión
- En los precios debería de haber algún . o , para evitar confusión en el usuario
- Cuando entras en la página de MercadoPago tarda en cargar
- Cuando estás en la sección del flujo de compra (dentro de mercado pago), queres volver para atrás te sale un error. También cuando realizas un pago como es en efectivo, queres volver a la página principal, también te sale un cartel de error.
- Cuando realizas una compra con éxito y queres volver a la página principal te sale una página de error

![buscador-no aparece login-carrito](https://github.com/leocouar/White-label/assets/153852816/a76226ac-3f32-45db-8210-a3e76d0443d6)
![agregar   o ,](https://github.com/leocouar/White-label/assets/153852816/340e65f6-e056-4c0a-a034-5a9d45b05f01)
![error](https://github.com/leocouar/White-label/assets/153852816/248d6b19-239a-4c7d-bed9-4eec4be17fc4)

2024-01-26 20:48 UTC, leocouar approved these changes

2024-01-31 17:47 UTC, candelamattioli submitted a review, later dismissed
- La compra se realiza con éxito pero cuando se hace click en el botón de “Volver al sitio” también aparece el cartel de error
- Cuando se quiere volver para la página principal estando en MercadoPago la opción es “Volver a IDEAAS”. Además si se vuelve para atrás sale un cartel de error.
- Faltaría la opción de pagar con puntos

![error fujodecompra](https://github.com/leocouar/White-label/assets/153852816/bfa4eced-38e3-4d8f-a3c3-e3fd426d603e)

2024-02-01 20:54 UTC, lautarobordino approved these changes
Aprobado

2024-02-01 20:55 UTC, merged