Vista de imagenes de productos/ Edicion de productos
leocouar/White-label pull request #150
Opened 2024-01-23 19:40 UTC by EnzoCepeda

Se arreglo la carga de imagenes de productos, y su vista al clickear la miniatura .
Se arreglo la edicion de producto siendo ADMIN/OWNER del store.
Falta la eliminacion de imagenes , estoy esperando a alan que lo haga desde el backend.

2024-01-24 17:02 UTC, candelamattioli requested changes
- En las imágenes miniatura del producto, cuando pasas dichas imágenes con la barra hacia los costados y queda en un punto, cuando se selecciona otro producto, dicha barra sigue en el mismo lugar.
- **Se puede borrar la imagen de cualquier comercio desde Comerciante**
- Visual: Cuando seleccionas dicha opción, lo primero que aparece es el footer
(Ver tarjeta Problemas para cargar imágenes a un producto)

![barrita de prod](https://github.com/leocouar/White-label/assets/153852816/eb382473-ca15-488b-9e0c-ce22e0fc98d2)
![barrita prod2](https://github.com/leocouar/White-label/assets/153852816/108571b9-b07f-44c2-b754-693b0d5744f9)

2024-01-25 18:05 UTC, leocouar reviewed
la lógica de owner no es la correspondiente, igualmente ya estoy trabajando en un hook para poder implementarlo.

2024-01-25 18:05 UTC, leocouar commented on components/products/ProductImage.js
cuando negas algo con !variable no es lo mismo que false porque esta expresion toma a null tambien.
var miVariable = null;
var negacion = !miVariable;

console.log(negacion); // Esto imprimirá: true

2024-01-25 18:05 UTC, leocouar commented on components/ownerAuthorization.js
esto desencadena conflictos con otros cambios

2024-01-25 18:05 UTC, leocouar commented on pages/products/update/[id].js
el SEO no va aca.

2024-01-26 20:49 UTC, leocouar approved these changes

2024-02-02 22:10 UTC, candelamattioli commented
Aún se puede borrar la imagen de cualquier comercio desde Comerciante

2024-02-15 17:40 UTC, closed without merging