User points
leocouar/White-label pull request #163
Opened 2024-02-02 17:54 UTC by EnzoCepeda

- Se agrego la carga de puntos desde la seccion admin a un usuario
- Se agregaron los campos en NewProduct para agregar los puntos de cada producto
- Se rediseño la parte visual de la tarjeta de productos ya que era la que se usaba en dulcebebe

2024-02-05 17:14 UTC, leocouar commented on components/products/NewProduct.js
No hay que borrar comentarios de explicacion de codigo en este caso tiene relevancia aunque se debe a una mala practica

2024-02-05 17:14 UTC, leocouar commented on components/wallet/index.js
valores en condicion de twins revisar

2024-02-05 19:15 UTC, candelamattioli commented
Actualmente no se puede acceder a Editar un usuario desde administración para agregar puntos
Cuando se crea un producto, no está el campo para agregar puntos


ding No se puede editar un usuario.mp4…

2024-02-05 19:15 UTC, candelamattioli reviewed
Uploading No se puede editar un usuario.mp4…

2024-02-05 19:23 UTC, candelamattioli requested changes
Actualmente no se puede acceder a Editar un usuario desde administración para agregar puntos
Cuando se crea un producto, no está el campo para agregar puntos

2024-02-06 20:10 UTC, candelamattioli reviewed
- Los resultados son los esperados, ya se pueden agregar y quitar puntos a un usuario desde el admin para los usuarios

- Cuando agregas puntos, sale un cartel de Page not found por unos segundos y se va

- Debería de haber un límite de puntos

Ver tarjeta de trello

2024-02-15 18:56 UTC, leocouar approved these changes

2024-02-15 20:47 UTC, closed without merging