User nav options
leocouar/White-label pull request #171
Opened 2024-02-27 19:04 UTC by EnzoCepeda

Se agrego las opciones de usuario en el nav acuando se loguea
opciones mis compras, mi billetera, mis datos y log out

2024-02-28 19:15 UTC, leocouar approved these changes

2024-02-28 20:26 UTC, candelamattioli requested changes
- En Mis compras, el precio Total se podría poner con puntos, al igual que el Precio Unitaro
- - En el Checkout se podría poner de un color azul o algo para que el usuario se de cuenta que puede hacer click ahí
→todo esto es más que nada visual
![Mis compras](https://github.com/leocouar/White-label/assets/153852816/51142c47-3699-455c-ba77-c57d7b2fa0d6)

- En sección Admin, cuando vas a Mi billetera, a simple vista no se ven los puntos, y cuando se hace click en esta no hace ninguna acción. Tampoco si se agregan o quitan puntos aparece nada.

https://github.com/leocouar/White-label/assets/153852816/dc141c52-9d9e-4385-b5d9-26637924a05b


→En un usuario de comercio si aparecen los puntos
- En Mis datos hay veces que no termina de cargar dicha opción

https://github.com/leocouar/White-label/assets/153852816/5fb927d4-ff5e-4c89-9bfe-8606314679e9

2024-03-05 20:16 UTC, candelamattioli commented
Los resultados son los esperados

- Se podría poner un limite de puntos

2024-03-05 20:16 UTC, candelamattioli approved these changes

2024-03-06 16:22 UTC, merged