Login para usuarios de comercio/ Redirecciones del login
leocouar/White-label pull request #177
Opened 2024-03-05 20:07 UTC by EnzoCepeda

Se cambio la redirección del login según el rol del usuario ingresado.
si el usuario es OWNER , te lleva a la pagina "/stores/list"
si el usuario es CUSTOMER , te lleva a la pagina principal "/"
si el usuario es ADMIN , te lleva a la pagina de administración "/admin".

2024-03-05 20:25 UTC, candelamattioli commented
Los resultados son los esperados

2024-03-05 20:25 UTC, candelamattioli approved these changes

2024-03-06 16:33 UTC, lautarobordino requested changes
Por favor eliminar el console.log de la linea 15, mas allá de que no hay que dejar ningún log, encima este es un log de session que deja expuesta info sensible.
Y ya que vas a modificar esto, agregale los '?' a session y user en la linea 46 para evitar conflictos cuando no haya sesión iniciada.

2024-03-06 18:31 UTC, lautarobordino approved these changes
Jueguee

2024-03-06 18:31 UTC, merged