Cart button
leocouar/White-label pull request #184
Opened 2024-03-14 18:26 UTC by EnzoCepeda

2024-03-14 18:45 UTC, EnzoCepeda commented
Se cambio el nombre del boton agregar al carrito por comprar.

2024-03-19 20:56 UTC, leocouar requested changes
Establecer una descripción es necesario para un mejor control podes decir el componente que modificaste pero tenes que ser mas especifico con los cambios que implementas.
También es necesario saber que es lo que se envia en el commit ya que repetidamente estas enviando cambios en userService.js y en [...nextauth].js

2024-03-19 20:56 UTC, leocouar commented on pages/api/auth/[...nextauth].js
Este cambio no corresponde en el titulo de la tarea

2024-03-19 20:56 UTC, leocouar commented on services/userService.js
No corresponde

2024-03-20 17:59 UTC, closed without merging